name: SonarCloud Security Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for analysis

      # 3️⃣ Build project (compile Java)
      - name: Build project
        run: mvn clean install -DskipTests

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify -DskipTests org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=cybersource_handler -Dsonar.projectName='cybersource_handler'

      # - name: Wait for Analysis Report
      #   run: sleep 20

      # - name: Check for High Security Issues
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     count=$(curl -s -u "$SONAR_TOKEN }}:" \
      #       "https://sonarcloud.io/api/issues/search?componentKeys=botian123123_sonarQubeTest&types=VULNERABILITY&severities=CRITICAL,BLOCKER" \
      #       | jq '.total')
      #     echo "Found $count critical/blocker vulnerabilities"
      #     if [ "$count" -gt 0 ]; then
      #       echo "❌ Security issues detected: $count"
      #       exit 1
      #     else
      #       echo "✅ No high severity security issues found."
      #     fi
